In [ ]:
#https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html#sphx-glr-beginner-blitz-neural-networks-tutorial-py
#Special thanks to Balint

In [ ]:
#hide
!pip install -Uqq fastbook
import fastbook
fastbook.setup_book()

In [ ]:
#hide
from fastai.vision.all import *
from fastbook import *
import os

matplotlib.rc('image', cmap='Greys')

In [ ]:
path = untar_data(URLs.MNIST)

In [ ]:
path

In [ ]:
#hide
Path.BASE_PATH = path

In [ ]:
path.ls()

## Putting It All Together

In [ ]:
def get_data(dirname,x):
    targetDir = path/dirname/x
    targetImages = targetDir.ls().sorted()
    targetTensors = [tensor(Image.open(o)) for o in targetImages]
    targetStacked = torch.stack(targetTensors).float()/255
    return targetStacked

In [ ]:
def get_dataset_len(dirname,x):
    return len((path/dirname/x).ls())

In [ ]:
train_x = torch.cat([get_data("training","0"), 
                     get_data("training","1"),
                     get_data("training","2"), 
                     get_data("training","3"),
                     get_data("training","4"), 
                     get_data("training","5"),
                     get_data("training","6"), 
                     get_data("training","7"),
                     get_data("training","8"), 
                     get_data("training","9")]).view(-1, 28*28)   

In [ ]:
train_y = tensor([1]*get_dataset_len("training","0") + 
                  [0]*get_dataset_len("training","1") +
                  [0]*get_dataset_len("training","2") +
                  [0]*get_dataset_len("training","3") +
                  [0]*get_dataset_len("training","4") +
                  [0]*get_dataset_len("training","5") +
                  [0]*get_dataset_len("training","6") +
                  [0]*get_dataset_len("training","7") + 
                  [0]*get_dataset_len("training","8") +
                  [0]*get_dataset_len("training","9")).unsqueeze(1) 
train_y = torch.cat((train_y,
           tensor([0]*get_dataset_len("training","0") + 
                  [1]*get_dataset_len("training","1") +
                  [0]*get_dataset_len("training","2") +
                  [0]*get_dataset_len("training","3") +
                  [0]*get_dataset_len("training","4") +
                  [0]*get_dataset_len("training","5") +
                  [0]*get_dataset_len("training","6") +
                  [0]*get_dataset_len("training","7") + 
                  [0]*get_dataset_len("training","8") +
                  [0]*get_dataset_len("training","9")).unsqueeze(1)),1)
train_y = torch.cat((train_y,
           tensor([0]*get_dataset_len("training","0") + 
                  [0]*get_dataset_len("training","1") +
                  [1]*get_dataset_len("training","2") +
                  [0]*get_dataset_len("training","3") +
                  [0]*get_dataset_len("training","4") +
                  [0]*get_dataset_len("training","5") +
                  [0]*get_dataset_len("training","6") +
                  [0]*get_dataset_len("training","7") + 
                  [0]*get_dataset_len("training","8") +
                  [0]*get_dataset_len("training","9")).unsqueeze(1)),1)
train_y = torch.cat((train_y,
           tensor([0]*get_dataset_len("training","0") + 
                  [0]*get_dataset_len("training","1") +
                  [0]*get_dataset_len("training","2") +
                  [1]*get_dataset_len("training","3") +
                  [0]*get_dataset_len("training","4") +
                  [0]*get_dataset_len("training","5") +
                  [0]*get_dataset_len("training","6") +
                  [0]*get_dataset_len("training","7") + 
                  [0]*get_dataset_len("training","8") +
                  [0]*get_dataset_len("training","9")).unsqueeze(1)),1)
train_y = torch.cat((train_y,
           tensor([0]*get_dataset_len("training","0") + 
                  [0]*get_dataset_len("training","1") +
                  [0]*get_dataset_len("training","2") +
                  [0]*get_dataset_len("training","3") +
                  [1]*get_dataset_len("training","4") +
                  [0]*get_dataset_len("training","5") +
                  [0]*get_dataset_len("training","6") +
                  [0]*get_dataset_len("training","7") + 
                  [0]*get_dataset_len("training","8") +
                  [0]*get_dataset_len("training","9")).unsqueeze(1)),1)
train_y = torch.cat((train_y,
           tensor([0]*get_dataset_len("training","0") + 
                  [0]*get_dataset_len("training","1") +
                  [0]*get_dataset_len("training","2") +
                  [0]*get_dataset_len("training","3") +
                  [0]*get_dataset_len("training","4") +
                  [1]*get_dataset_len("training","5") +
                  [0]*get_dataset_len("training","6") +
                  [0]*get_dataset_len("training","7") + 
                  [0]*get_dataset_len("training","8") +
                  [0]*get_dataset_len("training","9")).unsqueeze(1)),1)
train_y = torch.cat((train_y,
           tensor([0]*get_dataset_len("training","0") + 
                  [0]*get_dataset_len("training","1") +
                  [0]*get_dataset_len("training","2") +
                  [0]*get_dataset_len("training","3") +
                  [0]*get_dataset_len("training","4") +
                  [0]*get_dataset_len("training","5") +
                  [1]*get_dataset_len("training","6") +
                  [0]*get_dataset_len("training","7") + 
                  [0]*get_dataset_len("training","8") +
                  [0]*get_dataset_len("training","9")).unsqueeze(1)),1)
train_y = torch.cat((train_y,
           tensor([0]*get_dataset_len("training","0") + 
                  [0]*get_dataset_len("training","1") +
                  [0]*get_dataset_len("training","2") +
                  [0]*get_dataset_len("training","3") +
                  [0]*get_dataset_len("training","4") +
                  [0]*get_dataset_len("training","5") +
                  [0]*get_dataset_len("training","6") +
                  [1]*get_dataset_len("training","7") + 
                  [0]*get_dataset_len("training","8") +
                  [0]*get_dataset_len("training","9")).unsqueeze(1)),1)
train_y = torch.cat((train_y,
           tensor([0]*get_dataset_len("training","0") + 
                  [0]*get_dataset_len("training","1") +
                  [0]*get_dataset_len("training","2") +
                  [0]*get_dataset_len("training","3") +
                  [0]*get_dataset_len("training","4") +
                  [0]*get_dataset_len("training","5") +
                  [0]*get_dataset_len("training","6") +
                  [0]*get_dataset_len("training","7") + 
                  [1]*get_dataset_len("training","8") +
                  [0]*get_dataset_len("training","9")).unsqueeze(1)),1)
train_y = torch.cat((train_y,
           tensor([0]*get_dataset_len("training","0") + 
                  [0]*get_dataset_len("training","1") +
                  [0]*get_dataset_len("training","2") +
                  [0]*get_dataset_len("training","3") +
                  [0]*get_dataset_len("training","4") +
                  [0]*get_dataset_len("training","5") +
                  [0]*get_dataset_len("training","6") +
                  [0]*get_dataset_len("training","7") + 
                  [0]*get_dataset_len("training","8") +
                  [1]*get_dataset_len("training","9")).unsqueeze(1)),1)

In [ ]:
train_x.shape,train_y.shape

In [ ]:
valid_x = torch.cat([get_data("testing","0"), 
                     get_data("testing","1"),
                     get_data("testing","2"), 
                     get_data("testing","3"),
                     get_data("testing","4"), 
                     get_data("testing","5"),
                     get_data("testing","6"), 
                     get_data("testing","7"),
                     get_data("testing","8"), 
                     get_data("testing","9")]).view(-1, 28*28)   

In [ ]:
valid_y = tensor([1]*get_dataset_len("testing","0") + 
                  [0]*get_dataset_len("testing","1") +
                  [0]*get_dataset_len("testing","2") +
                  [0]*get_dataset_len("testing","3") +
                  [0]*get_dataset_len("testing","4") +
                  [0]*get_dataset_len("testing","5") +
                  [0]*get_dataset_len("testing","6") +
                  [0]*get_dataset_len("testing","7") + 
                  [0]*get_dataset_len("testing","8") +
                  [0]*get_dataset_len("testing","9")).unsqueeze(1) 
valid_y = torch.cat((valid_y,
           tensor([0]*get_dataset_len("testing","0") + 
                  [1]*get_dataset_len("testing","1") +
                  [0]*get_dataset_len("testing","2") +
                  [0]*get_dataset_len("testing","3") +
                  [0]*get_dataset_len("testing","4") +
                  [0]*get_dataset_len("testing","5") +
                  [0]*get_dataset_len("testing","6") +
                  [0]*get_dataset_len("testing","7") + 
                  [0]*get_dataset_len("testing","8") +
                  [0]*get_dataset_len("testing","9")).unsqueeze(1)),1)
valid_y = torch.cat((valid_y,
           tensor([0]*get_dataset_len("testing","0") + 
                  [0]*get_dataset_len("testing","1") +
                  [1]*get_dataset_len("testing","2") +
                  [0]*get_dataset_len("testing","3") +
                  [0]*get_dataset_len("testing","4") +
                  [0]*get_dataset_len("testing","5") +
                  [0]*get_dataset_len("testing","6") +
                  [0]*get_dataset_len("testing","7") + 
                  [0]*get_dataset_len("testing","8") +
                  [0]*get_dataset_len("testing","9")).unsqueeze(1)),1)
valid_y = torch.cat((valid_y,
           tensor([0]*get_dataset_len("testing","0") + 
                  [0]*get_dataset_len("testing","1") +
                  [0]*get_dataset_len("testing","2") +
                  [1]*get_dataset_len("testing","3") +
                  [0]*get_dataset_len("testing","4") +
                  [0]*get_dataset_len("testing","5") +
                  [0]*get_dataset_len("testing","6") +
                  [0]*get_dataset_len("testing","7") + 
                  [0]*get_dataset_len("testing","8") +
                  [0]*get_dataset_len("testing","9")).unsqueeze(1)),1)
valid_y = torch.cat((valid_y,
           tensor([0]*get_dataset_len("testing","0") + 
                  [0]*get_dataset_len("testing","1") +
                  [0]*get_dataset_len("testing","2") +
                  [0]*get_dataset_len("testing","3") +
                  [1]*get_dataset_len("testing","4") +
                  [0]*get_dataset_len("testing","5") +
                  [0]*get_dataset_len("testing","6") +
                  [0]*get_dataset_len("testing","7") + 
                  [0]*get_dataset_len("testing","8") +
                  [0]*get_dataset_len("testing","9")).unsqueeze(1)),1)
valid_y = torch.cat((valid_y,
           tensor([0]*get_dataset_len("testing","0") + 
                  [0]*get_dataset_len("testing","1") +
                  [0]*get_dataset_len("testing","2") +
                  [0]*get_dataset_len("testing","3") +
                  [0]*get_dataset_len("testing","4") +
                  [1]*get_dataset_len("testing","5") +
                  [0]*get_dataset_len("testing","6") +
                  [0]*get_dataset_len("testing","7") + 
                  [0]*get_dataset_len("testing","8") +
                  [0]*get_dataset_len("testing","9")).unsqueeze(1)),1)
valid_y = torch.cat((valid_y,
           tensor([0]*get_dataset_len("testing","0") + 
                  [0]*get_dataset_len("testing","1") +
                  [0]*get_dataset_len("testing","2") +
                  [0]*get_dataset_len("testing","3") +
                  [0]*get_dataset_len("testing","4") +
                  [0]*get_dataset_len("testing","5") +
                  [1]*get_dataset_len("testing","6") +
                  [0]*get_dataset_len("testing","7") + 
                  [0]*get_dataset_len("testing","8") +
                  [0]*get_dataset_len("testing","9")).unsqueeze(1)),1)
valid_y = torch.cat((valid_y,
           tensor([0]*get_dataset_len("testing","0") + 
                  [0]*get_dataset_len("testing","1") +
                  [0]*get_dataset_len("testing","2") +
                  [0]*get_dataset_len("testing","3") +
                  [0]*get_dataset_len("testing","4") +
                  [0]*get_dataset_len("testing","5") +
                  [0]*get_dataset_len("testing","6") +
                  [1]*get_dataset_len("testing","7") + 
                  [0]*get_dataset_len("testing","8") +
                  [0]*get_dataset_len("testing","9")).unsqueeze(1)),1)
valid_y = torch.cat((valid_y,
           tensor([0]*get_dataset_len("testing","0") + 
                  [0]*get_dataset_len("testing","1") +
                  [0]*get_dataset_len("testing","2") +
                  [0]*get_dataset_len("testing","3") +
                  [0]*get_dataset_len("testing","4") +
                  [0]*get_dataset_len("testing","5") +
                  [0]*get_dataset_len("testing","6") +
                  [0]*get_dataset_len("testing","7") + 
                  [1]*get_dataset_len("testing","8") +
                  [0]*get_dataset_len("testing","9")).unsqueeze(1)),1)
valid_y = torch.cat((valid_y,
           tensor([0]*get_dataset_len("testing","0") + 
                  [0]*get_dataset_len("testing","1") +
                  [0]*get_dataset_len("testing","2") +
                  [0]*get_dataset_len("testing","3") +
                  [0]*get_dataset_len("testing","4") +
                  [0]*get_dataset_len("testing","5") +
                  [0]*get_dataset_len("testing","6") +
                  [0]*get_dataset_len("testing","7") + 
                  [0]*get_dataset_len("testing","8") +
                  [1]*get_dataset_len("testing","9")).unsqueeze(1)),1)

In [ ]:
valid_x.shape,valid_y.shape

In [ ]:
def init_params(size, std=1.0): return (torch.randn(size)*std).requires_grad_()

In [ ]:
def mnist_loss(predictions, targets):
    predictions = predictions.sigmoid()
    return torch.where(targets==1, 1-predictions, predictions).mean()

In [ ]:
def pick_a_file(n):
    if n == 0:   x = 'different for everyone'+'/.fastai/data/mnist_png/testing/0/1001.png'
    elif n == 1: x = 'different for everyone'+'/.fastai/data/mnist_png/testing/1/1004.png'
    elif n == 2: x = 'different for everyone'+'/.fastai/data/mnist_png/testing/2/1002.png'
    elif n == 3: x = 'different for everyone'+'/.fastai/data/mnist_png/testing/3/1020.png'
    elif n == 4: x = 'different for everyone'+'/.fastai/data/mnist_png/testing/4/1010.png'
    elif n == 5: x = 'different for everyone'+'/.fastai/data/mnist_png/testing/5/1003.png'
    elif n == 6: x = 'different for everyone'+'/.fastai/data/mnist_png/testing/6/100.png'
    elif n == 7: x = 'different for everyone'+'/.fastai/data/mnist_png/testing/7/0.png'
    elif n == 8: x = 'different for everyone'+'/.fastai/data/mnist_png/testing/8/1007.png'
    elif n == 9: x = 'different for everyone'+'/.fastai/data/mnist_png/testing/9/1000.png'
 
    return x

In [ ]:
simple_net = nn.Sequential(
    nn.Linear(28*28,30),
    nn.ReLU(),
    nn.Linear(30,10),
)

In [ ]:
def batch_accuracy(xb, yb):
    preds = xb.sigmoid()
    correct = (preds>0.5) == yb
    return correct.float().mean()

In [ ]:
dset = list(zip(train_x,train_y))
valid_dset = list(zip(valid_x,valid_y))

dl = DataLoader(dset, batch_size=256)
valid_dl = DataLoader(valid_dset, batch_size=256)
dls = DataLoaders(dl, valid_dl)

w1 = init_params((28*28,30))
b1 = init_params(30)
w2 = init_params((30,10))
b2 = init_params(10)
params = w1,b1,w2,b2

learn = Learner(dls, simple_net, opt_func=SGD,
                loss_func=mnist_loss, metrics=batch_accuracy)
learn.fit(10,0.1)

In [ ]:
for i in range (10):

    f=pick_a_file(i);
    targetTensors = tensor(Image.open(f)).float()/255
    targetTensorsv=targetTensors.view(-1,28*28);
    learn.model.eval()
    res=learn.model(targetTensorsv)
    head, tail = os.path.split(f)
    print(tail, res)

### Going Deeper

In [ ]:
dlsEasy = ImageDataLoaders.from_folder(path, train="training", valid="testing")

In [ ]:
learnEasy = cnn_learner(dlsEasy, resnet18, pretrained=False,
               loss_func=F.cross_entropy, metrics=accuracy)

In [ ]:
learnEasy.fit_one_cycle(1, 0.1)

In [ ]:
for i in range (10):
    f=pick_a_file(i);
    targetTensors = tensor(Image.open(f)).float()/255
    targetTensorsRGB=targetTensors.repeat(3, 1, 1)
    learnEasy.model.eval()
    res=learnEasy.model(targetTensorsRGB.view(1,3,28,28).cuda())
    head, tail = os.path.split(f)
    #print(torch.argmax(res))
    buf = "%s" % torch.argmax(res);
    print("Truth:", head[-1],' Detected:', buf[7], "Filename:", tail)


## Jargon Recap

## Questionnaire

1. How is a grayscale image represented on a computer? How about a color image?
1. How are the files and folders in the `MNIST_SAMPLE` dataset structured? Why?
1. Explain how the "pixel similarity" approach to classifying digits works.
1. What is a list comprehension? Create one now that selects odd numbers from a list and doubles them.
1. What is a "rank-3 tensor"?
1. What is the difference between tensor rank and shape? How do you get the rank from the shape?
1. What are RMSE and L1 norm?
1. How can you apply a calculation on thousands of numbers at once, many thousands of times faster than a Python loop?
1. Create a 3×3 tensor or array containing the numbers from 1 to 9. Double it. Select the bottom-right four numbers.
1. What is broadcasting?
1. Are metrics generally calculated using the training set, or the validation set? Why?
1. What is SGD?
1. Why does SGD use mini-batches?
1. What are the seven steps in SGD for machine learning?
1. How do we initialize the weights in a model?
1. What is "loss"?
1. Why can't we always use a high learning rate?
1. What is a "gradient"?
1. Do you need to know how to calculate gradients yourself?
1. Why can't we use accuracy as a loss function?
1. Draw the sigmoid function. What is special about its shape?
1. What is the difference between a loss function and a metric?
1. What is the function to calculate new weights using a learning rate?
1. What does the `DataLoader` class do?
1. Write pseudocode showing the basic steps taken in each epoch for SGD.
1. Create a function that, if passed two arguments `[1,2,3,4]` and `'abcd'`, returns `[(1, 'a'), (2, 'b'), (3, 'c'), (4, 'd')]`. What is special about that output data structure?
1. What does `view` do in PyTorch?
1. What are the "bias" parameters in a neural network? Why do we need them?
1. What does the `@` operator do in Python?
1. What does the `backward` method do?
1. Why do we have to zero the gradients?
1. What information do we have to pass to `Learner`?
1. Show Python or pseudocode for the basic steps of a training loop.
1. What is "ReLU"? Draw a plot of it for values from `-2` to `+2`.
1. What is an "activation function"?
1. What's the difference between `F.relu` and `nn.ReLU`?
1. The universal approximation theorem shows that any function can be approximated as closely as needed using just one nonlinearity. So why do we normally use more?

### Further Research

1. Create your own implementation of `Learner` from scratch, based on the training loop shown in this chapter.
1. Complete all the steps in this chapter using the full MNIST datasets (that is, for all digits, not just 3s and 7s). This is a significant project and will take you quite a bit of time to complete! You'll need to do some of your own research to figure out how to overcome some obstacles you'll meet on the way.